name: deployment to webapp node js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: install deps
      run: npm install
    - name: build
      run: npm run build
    - name: test
      run: npm run test
    - name: artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: my-artifact-nodejs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: download-artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact-nodejs
    - name: list file
      run: ls